### PR TITLE
Add USE_SSE Checks To Fix Compile on Linux

### LINKED ISSUE #617: Error during make with Lut1DOp.cpp.o from v1.1.0 on CentOS docker build
Having an issue where build fails after hitting this section of the build:
`[ 42%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/Lut1DOp.cpp.o`

Has anyone seen this and know of any work arounds?

Full output of my docker RUN command:
```
RUN cd ~/source && 	git clone https://github.com/imageworks/OpenColorIO.git && 	cd OpenColorIO && 	git checkout tags/v1.1.0 && 	source scl_source enable devtoolset-6 && 	scl enable devtoolset-6 bash && 	cmake --DCMAKE_INSTALL_PREFIX:PATH=/usr/local --OCIO_BUILD_GPU_TESTS=OFF . && 	make -j2 && 	make install
Cloning into 'OpenColorIO'...
Note: checking out 'tags/v1.1.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at bc40c8a... update changelog (#496)
-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /opt/rh/devtoolset-6/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-6/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-6/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-6/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting Build Type to: RelWithDebInfo
-- Setting Namespace to: OpenColorIO
-- Exec prefix not specified, defaulting to /usr/local
-- Use Boost Ptr: OFF
-- Setting python bin to: python
Python library: /usr/lib64/python2.7/config/libpython2.7.so
-- Setting EXTDIST_BINPATH: /root/source/OpenColorIO/ext/dist/bin
-- Setting EXTDIST_PYTHONPATH: /root/source/OpenColorIO/ext/dist/lib/python2.7/site-packages
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
-- Generate Documentation: OFF
-- SSE Optimizations: ON
-- Could NOT find Truelight (missing: Truelight_INCLUDE_DIR Truelight_LIBRARIES Truelight_LIBRARY_DIR) 
-- Not building truelight transform support. Add the flag -D TRUELIGHT_INSTALL_PATH=... or set the TRUELIGHT_ROOT environment variable
-- Create OpenColorABI.h from OpenColorABI.h.in
-- Setting OCIO SOVERSION to: 1
-- Setting OCIO SOVERSION to: 1
-- Create OpenColorIO.pc from OpenColorIO.pc.in
-- Build Unit Tests: ON
-- Create ocio_core_tests.sh.in from ocio_core_tests.sh
-- Found OIIO library /usr/local/lib64/libOpenImageIO.so
-- Found OIIO includes /usr/local/include
-- Found Ilmbase includes /usr/local/include
-- Found OpenGL: /usr/lib64/libGL.so   
-- Found OpenGL library /usr/lib64/libGL.so;/usr/lib64/libGLU.so
-- Found OpenGL includes /usr/include
-- Found GLUT: /usr/lib64/libglut.so  
-- Found GLUT library /usr/lib64/libglut.so
-- Found GLEW library /usr/lib64/libGLEW.so
-- Found GLEW includes /usr/include
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Using bundled lcms.
-- Could NOT find Nuke (missing: Nuke_INCLUDE_DIR Nuke_LIBRARIES Nuke_LIBRARY_DIR) 
-- Not building Nuke plugins. Add the flag -D NUKE_INSTALL_PATH=... or set the NDK_PATH environment variable
-- Python library to include 'lib' prefix: OFF
-- Python 2.7 okay (UCS: ucs4), will build the Python bindings against /usr/include/python2.7
-- Python variant path is lib/python2.7/site-packages
-- Found PythonLibs: /usr/lib64/python2.7/config/libpython2.7.so (found version "2.7.5") 
PYTHON_VARIANT_PATH: lib/python2.7/site-packages
-- Configuring done
-- Generating done
-- Build files have been written to: /root/source/OpenColorIO
Scanning dependencies of target YAML_CPP_LOCAL
Scanning dependencies of target tinyxml
[  1%] Creating directories for 'YAML_CPP_LOCAL'
[  1%] Creating directories for 'tinyxml'
[  2%] Performing download step (verify and extract) for 'tinyxml'
[  2%] Performing download step (verify and extract) for 'YAML_CPP_LOCAL'
CMake Warning at /root/source/OpenColorIO/YAML_CPP_LOCAL-prefix/src/YAML_CPP_LOCAL-stamp/verify-YAML_CPP_LOCAL.cmake:15 (message):
  File will not be verified since no URL_HASH specified

CMake Warning at /root/source/OpenColorIO/tinyxml-prefix/src/tinyxml-stamp/verify-tinyxml.cmake:15 (message):
  File will not be verified since no URL_HASH specified



-- extracting...
     src='/root/source/OpenColorIO/ext/yaml-cpp-0.3.0.tar.gz'
     dst='/root/source/OpenColorIO/ext/yaml-cpp'
-- extracting...
     src='/root/source/OpenColorIO/ext/tinyxml_2_6_1.tar.gz'
     dst='/root/source/OpenColorIO/ext/tinyxml'
-- extracting... [tar xfz]
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  2%] Performing patch step for 'YAML_CPP_LOCAL'
[  3%] Performing patch step for 'tinyxml'
[  3%] No update step for 'YAML_CPP_LOCAL'
[  3%] No update step for 'tinyxml'
[  4%] Performing configure step for 'YAML_CPP_LOCAL'
[  4%] Performing configure step for 'tinyxml'
CMake Deprecation Warning at CMakeLists.txt:9 (cmake_policy):
  The OLD behavior for policy CMP0012 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Deprecation Warning at CMakeLists.txt:13 (cmake_policy):
  The OLD behavior for policy CMP0015 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- The C compiler identification is GNU 6.3.1
-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /opt/rh/devtoolset-6/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-6/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-6/root/usr/bin/cc -- works
-- Check for working C compiler: /opt/rh/devtoolset-6/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-6/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-6/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-6/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Check for working CXX compiler: /opt/rh/devtoolset-6/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Detecting CXX compile features - done
-- Generating done
-- Build files have been written to: /root/source/OpenColorIO/ext/build/tinyxml
-- Performing Test FLAG_WEXTRA
[  5%] Performing build step for 'tinyxml'
Scanning dependencies of target tinyxml
[ 20%] Building CXX object CMakeFiles/tinyxml.dir/tinystr.cpp.o
[ 40%] Building CXX object CMakeFiles/tinyxml.dir/tinyxml.cpp.o
-- Performing Test FLAG_WEXTRA - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /root/source/OpenColorIO/ext/build/yaml-cpp
[  5%] Performing build step for 'YAML_CPP_LOCAL'
Scanning dependencies of target yaml-cpp
[  3%] Building CXX object CMakeFiles/yaml-cpp.dir/src/aliasmanager.cpp.o
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/aliasmanager.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:20:17: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   Iterator(std::auto_ptr<IterPriv> pData);
                 ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/aliasmanager.cpp:2:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/aliasmanager.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:36:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<IterPriv> m_pData;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/aliasmanager.cpp:2:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/aliasmanager.cpp:2:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:43:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Node> Clone() const;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/aliasmanager.cpp:2:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/aliasmanager.cpp:2:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:117:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<NodeOwnership> m_pOwnership;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/aliasmanager.cpp:2:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[  7%] Building CXX object CMakeFiles/yaml-cpp.dir/src/binary.cpp.o
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/binary.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:20:17: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   Iterator(std::auto_ptr<IterPriv> pData);
                 ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/binary.cpp:2:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/binary.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:36:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<IterPriv> m_pData;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/binary.cpp:2:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/binary.cpp:2:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:43:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Node> Clone() const;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/binary.cpp:2:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/binary.cpp:2:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:117:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<NodeOwnership> m_pOwnership;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/binary.cpp:2:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[ 60%] Building CXX object CMakeFiles/tinyxml.dir/tinyxmlerror.cpp.o
[ 10%] Building CXX object CMakeFiles/yaml-cpp.dir/src/conversion.cpp.o
[ 80%] Building CXX object CMakeFiles/tinyxml.dir/tinyxmlparser.cpp.o
[ 14%] Building CXX object CMakeFiles/yaml-cpp.dir/src/directives.cpp.o
[ 17%] Building CXX object CMakeFiles/yaml-cpp.dir/src/emitfromevents.cpp.o
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitfromevents.cpp:2:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/emitter.h:105:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr <EmitterState> m_pState;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/emitter.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitfromevents.cpp:2:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[100%] Linking CXX static library libtinyxml.a
[100%] Built target tinyxml
[  5%] Performing install step for 'tinyxml'
[100%] Built target tinyxml
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /root/source/OpenColorIO/ext/dist/lib/libtinyxml.a
-- Installing: /root/source/OpenColorIO/ext/dist/include/tinyxml.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/tinystr.h
[  6%] Completed 'tinyxml'
[  6%] Built target tinyxml
Scanning dependencies of target LCMS
[  7%] Creating directories for 'LCMS'
[  7%] Performing download step (verify and extract) for 'LCMS'
CMake Warning at LCMS-stamp/verify-LCMS.cmake:15 (message):
  File will not be verified since no URL_HASH specified


-- extracting...
     src='/root/source/OpenColorIO/ext/lcms2-2.1.tar.gz'
     dst='/root/source/OpenColorIO/lcms2-prefix/src/LCMS'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  8%] Performing patch step for 'LCMS'
[  8%] No update step for 'LCMS'
[  8%] Performing configure step for 'LCMS'
-- The C compiler identification is GNU 6.3.1
[ 21%] Building CXX object CMakeFiles/yaml-cpp.dir/src/emitter.cpp.o
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /opt/rh/devtoolset-6/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-6/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:1:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/emitter.h:105:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr <EmitterState> m_pState;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/emitter.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:9:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h:30:17: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
  void push(std::auto_ptr<T> t) {
                 ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/emitter.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:9:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h:34:7: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
  std::auto_ptr<T> pop() {
       ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/emitter.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:9:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h: In member function 'std::auto_ptr<_Up> ptr_stack<T>::pop()':
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h:35:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<T> t(m_data.back());
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/emitter.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:10:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/src/setting.h: At global scope:
/root/source/OpenColorIO/ext/yaml-cpp/src/setting.h:24:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr <SettingChangeBase> set(const T& value);
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/emitter.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:10:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/src/setting.h:59:14: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
  inline std::auto_ptr <SettingChangeBase> Setting<T>::set(const T& value) {
              ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/emitter.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:10:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/src/setting.h: In member function 'std::auto_ptr<YAML::SettingChangeBase> YAML::Setting<T>::set(const T&)':
/root/source/OpenColorIO/ext/yaml-cpp/src/setting.h:60:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr <SettingChangeBase> pChange(new SettingChange<T> (this));
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/emitter.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:10:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/src/setting.h: At global scope:
/root/source/OpenColorIO/ext/yaml-cpp/src/setting.h:84:18: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   void push(std::auto_ptr <SettingChangeBase> pSettingChange) {
                  ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/emitter.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitter.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-6/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-6/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
[ 25%] Building CXX object CMakeFiles/yaml-cpp.dir/src/emitterstate.cpp.o
-- Detecting CXX compile features - done
-- Configuring done
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:9:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h:30:17: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
  void push(std::auto_ptr<T> t) {
                 ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:9:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h:34:7: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
  std::auto_ptr<T> pop() {
       ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:9:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h: In member function 'std::auto_ptr<T> ptr_stack<T>::pop()':
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h:35:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<T> t(m_data.back());
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:10:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/src/setting.h: At global scope:
/root/source/OpenColorIO/ext/yaml-cpp/src/setting.h:24:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr <SettingChangeBase> set(const T& value);
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:10:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/src/setting.h:59:14: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
  inline std::auto_ptr <SettingChangeBase> Setting<T>::set(const T& value) {
              ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:10:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/src/setting.h: In member function 'std::auto_ptr<YAML::SettingChangeBase> YAML::Setting<T>::set(const T&)':
/root/source/OpenColorIO/ext/yaml-cpp/src/setting.h:60:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr <SettingChangeBase> pChange(new SettingChange<T> (this));
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:10:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/src/setting.h: At global scope:
/root/source/OpenColorIO/ext/yaml-cpp/src/setting.h:84:18: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   void push(std::auto_ptr <SettingChangeBase> pSettingChange) {
                  ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
-- Generating done
-- Build files have been written to: /root/source/OpenColorIO/ext/build/lcms2
[  9%] Performing build step for 'LCMS'
Scanning dependencies of target lcms2
[  4%] Building C object CMakeFiles/lcms2.dir/src/cmscam02.c.o
/root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp: In member function 'void YAML::EmitterState::BeginGroup(YAML::GROUP_TYPE)':
/root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:54:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Group> pGroup(new Group(type));
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp: In member function 'void YAML::EmitterState::EndGroup(YAML::GROUP_TYPE)':
/root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:74:9: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
    std::auto_ptr<Group> pFinishedGroup = m_groups.pop();
         ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_stack.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/emitterstate.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[  8%] Building C object CMakeFiles/lcms2.dir/src/cmscgats.c.o
[ 28%] Building CXX object CMakeFiles/yaml-cpp.dir/src/emitterutils.cpp.o
[ 12%] Building C object CMakeFiles/lcms2.dir/src/cmscnvrt.c.o
[ 16%] Building C object CMakeFiles/lcms2.dir/src/cmserr.c.o
[ 20%] Building C object CMakeFiles/lcms2.dir/src/cmsgamma.c.o
[ 24%] Building C object CMakeFiles/lcms2.dir/src/cmsgmt.c.o
[ 28%] Building C object CMakeFiles/lcms2.dir/src/cmsintrp.c.o
[ 32%] Building C object CMakeFiles/lcms2.dir/src/cmsio0.c.o
[ 36%] Building C object CMakeFiles/lcms2.dir/src/cmsio1.c.o
[ 40%] Building C object CMakeFiles/lcms2.dir/src/cmslut.c.o
[ 44%] Building C object CMakeFiles/lcms2.dir/src/cmsmd5.c.o
[ 48%] Building C object CMakeFiles/lcms2.dir/src/cmsmtrx.c.o
[ 52%] Building C object CMakeFiles/lcms2.dir/src/cmsnamed.c.o
[ 56%] Building C object CMakeFiles/lcms2.dir/src/cmsopt.c.o
[ 32%] Building CXX object CMakeFiles/yaml-cpp.dir/src/exp.cpp.o
[ 60%] Building C object CMakeFiles/lcms2.dir/src/cmspack.c.o
[ 35%] Building CXX object CMakeFiles/yaml-cpp.dir/src/iterator.cpp.o
[ 64%] Building C object CMakeFiles/lcms2.dir/src/cmspcs.c.o
[ 68%] Building C object CMakeFiles/lcms2.dir/src/cmsplugin.c.o
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/iterator.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:20:17: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   Iterator(std::auto_ptr<IterPriv> pData);
                 ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/iterator.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/iterator.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:36:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<IterPriv> m_pData;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/iterator.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/iterator.cpp:1:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:43:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Node> Clone() const;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/iterator.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/iterator.cpp:1:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:117:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<NodeOwnership> m_pOwnership;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/iterator.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/root/source/OpenColorIO/ext/yaml-cpp/src/iterator.cpp:11:26: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
  Iterator::Iterator(std::auto_ptr<IterPriv> pData): m_pData(pData)
                          ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/iterator.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[ 72%] Building C object CMakeFiles/lcms2.dir/src/cmsps2.c.o
[ 39%] Building CXX object CMakeFiles/yaml-cpp.dir/src/node.cpp.o
[ 76%] Building C object CMakeFiles/lcms2.dir/src/cmssamp.c.o
[ 80%] Building C object CMakeFiles/lcms2.dir/src/cmssm.c.o
[ 84%] Building C object CMakeFiles/lcms2.dir/src/cmstypes.c.o
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:20:17: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   Iterator(std::auto_ptr<IterPriv> pData);
                 ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:36:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<IterPriv> m_pData;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:43:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Node> Clone() const;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:117:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<NodeOwnership> m_pOwnership;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:4:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/emitter.h:105:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr <EmitterState> m_pState;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.h:10:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:8:
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:32:23: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   void push_back(std::auto_ptr<T> t) {
                       ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:54:7: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
  std::auto_ptr<Node> Node::Clone() const
       ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp: In member function 'std::auto_ptr<YAML::Node> YAML::Node::Clone() const':
/root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:56:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Node> pNode(new Node);
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp: In member function 'YAML::Iterator YAML::Node::begin() const':
/root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:148:26: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
     return Iterator(std::auto_ptr<IterPriv>(new IterPriv(m_seqData.begin())));
                          ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:150:26: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
     return Iterator(std::auto_ptr<IterPriv>(new IterPriv(m_mapData.begin())));
                          ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp: In member function 'YAML::Iterator YAML::Node::end() const':
/root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:166:26: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
     return Iterator(std::auto_ptr<IterPriv>(new IterPriv(m_seqData.end())));
                          ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:168:26: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
     return Iterator(std::auto_ptr<IterPriv>(new IterPriv(m_mapData.end())));
                          ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/node.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[ 42%] Building CXX object CMakeFiles/yaml-cpp.dir/src/nodebuilder.cpp.o
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodebuilder.cpp:3:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:20:17: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   Iterator(std::auto_ptr<IterPriv> pData);
                 ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodebuilder.h:10,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodebuilder.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodebuilder.cpp:3:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:36:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<IterPriv> m_pData;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodebuilder.h:10,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodebuilder.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/nodebuilder.cpp:3:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:43:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Node> Clone() const;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodebuilder.h:10,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodebuilder.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/nodebuilder.cpp:3:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:117:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<NodeOwnership> m_pOwnership;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodebuilder.h:10,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodebuilder.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[ 88%] Building C object CMakeFiles/lcms2.dir/src/cmsvirt.c.o
[ 92%] Building C object CMakeFiles/lcms2.dir/src/cmswtpnt.c.o
[ 46%] Building CXX object CMakeFiles/yaml-cpp.dir/src/nodeownership.cpp.o
[ 96%] Building C object CMakeFiles/lcms2.dir/src/cmsxform.c.o
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.h:10:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:32:23: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   void push_back(std::auto_ptr<T> t) {
                       ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.h:10,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[100%] Linking C static library liblcms2.a
[100%] Built target lcms2
[  9%] Performing install step for 'LCMS'
[100%] Built target lcms2
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /root/source/OpenColorIO/ext/dist/lib/liblcms2.a
-- Installing: /root/source/OpenColorIO/ext/dist/include/lcms2.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/lcms2_plugin.h
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:20:17: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   Iterator(std::auto_ptr<IterPriv> pData);
                 ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.h:10,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:36:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<IterPriv> m_pData;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.h:10,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[  9%] Completed 'LCMS'
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.cpp:2:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:43:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Node> Clone() const;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.h:10,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.cpp:2:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:117:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<NodeOwnership> m_pOwnership;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.h:10,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.cpp: In member function 'YAML::Node& YAML::NodeOwnership::_Create()':
/root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.cpp:18:26: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   m_nodes.push_back(std::auto_ptr<Node>(new Node));
                          ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.h:10,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/nodeownership.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[  9%] Built target LCMS
[ 50%] Building CXX object CMakeFiles/yaml-cpp.dir/src/null.cpp.o
[ 53%] Building CXX object CMakeFiles/yaml-cpp.dir/src/ostream.cpp.o
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/null.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:20:17: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   Iterator(std::auto_ptr<IterPriv> pData);
                 ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/null.cpp:2:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/null.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:36:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<IterPriv> m_pData;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/null.cpp:2:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/null.cpp:2:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:43:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Node> Clone() const;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/null.cpp:2:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/null.cpp:2:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:117:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<NodeOwnership> m_pOwnership;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:9,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/null.cpp:2:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[ 57%] Building CXX object CMakeFiles/yaml-cpp.dir/src/parser.cpp.o
[ 60%] Building CXX object CMakeFiles/yaml-cpp.dir/src/regex.cpp.o
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:1:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/parser.h:46:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Scanner> m_pScanner;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/parser.h:12,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:1:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/parser.h:47:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Directives> m_pDirectives;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/parser.h:12,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:4:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:20:17: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   Iterator(std::auto_ptr<IterPriv> pData);
                 ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/parser.h:12,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:14:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:4:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/iterator.h:36:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<IterPriv> m_pData;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/parser.h:12,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:4:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:43:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Node> Clone() const;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/parser.h:12,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:4:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/node.h:117:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<NodeOwnership> m_pOwnership;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/parser.h:12,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.h:15:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:7:
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:32:23: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   void push_back(std::auto_ptr<T> t) {
                       ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/parser.h:12,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:8:0:
/root/source/OpenColorIO/ext/yaml-cpp/src/singledocparser.h:56:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<CollectionStack> m_pCollectionStack;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/parser.h:12,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/parser.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[ 64%] Building CXX object CMakeFiles/yaml-cpp.dir/src/scanner.cpp.o
[ 67%] Building CXX object CMakeFiles/yaml-cpp.dir/src/scanscalar.cpp.o
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.h:15:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:32:23: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   void push_back(std::auto_ptr<T> t) {
                       ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/root/source/OpenColorIO/ext/yaml-cpp/src/scanner.cpp: In member function 'void YAML::Scanner::StartStream()':
/root/source/OpenColorIO/ext/yaml-cpp/src/scanner.cpp:237:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<IndentMarker> pIndent(new IndentMarker(-1, IndentMarker::NONE));
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/root/source/OpenColorIO/ext/yaml-cpp/src/scanner.cpp: In member function 'YAML::Scanner::IndentMarker* YAML::Scanner::PushIndentTo(int, YAML::Scanner::IndentMarker::INDENT_TYPE)':
/root/source/OpenColorIO/ext/yaml-cpp/src/scanner.cpp:284:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<IndentMarker> pIndent(new IndentMarker(column, type));
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.h:15:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scanscalar.cpp:2:
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:32:23: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   void push_back(std::auto_ptr<T> t) {
                       ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scanscalar.cpp:2:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[ 71%] Building CXX object CMakeFiles/yaml-cpp.dir/src/scantag.cpp.o
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.h:15:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scantag.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:32:23: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   void push_back(std::auto_ptr<T> t) {
                       ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scantag.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[ 75%] Building CXX object CMakeFiles/yaml-cpp.dir/src/scantoken.cpp.o
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.h:15:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scantoken.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:32:23: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   void push_back(std::auto_ptr<T> t) {
                       ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scantoken.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[ 78%] Building CXX object CMakeFiles/yaml-cpp.dir/src/simplekey.cpp.o
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.h:15:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/simplekey.cpp:1:
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:32:23: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   void push_back(std::auto_ptr<T> t) {
                       ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:11,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.h:15,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/simplekey.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[ 82%] Building CXX object CMakeFiles/yaml-cpp.dir/src/singledocparser.cpp.o
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/singledocparser.cpp:1:0:
/root/source/OpenColorIO/ext/yaml-cpp/src/singledocparser.h:56:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<CollectionStack> m_pCollectionStack;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/singledocparser.h:13,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/singledocparser.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/scanner.h:15:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/singledocparser.cpp:6:
/root/source/OpenColorIO/ext/yaml-cpp/src/ptr_vector.h:32:23: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   void push_back(std::auto_ptr<T> t) {
                       ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/singledocparser.h:13,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/singledocparser.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[ 85%] Building CXX object CMakeFiles/yaml-cpp.dir/src/stream.cpp.o
[ 89%] Building CXX object CMakeFiles/yaml-cpp.dir/src/tag.cpp.o
[ 92%] Building CXX object CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.o
[ 96%] Building CXX object CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilderadapter.cpp.o
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/contrib/graphbuilder.cpp:1:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/parser.h:46:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Scanner> m_pScanner;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/parser.h:12,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/contrib/graphbuilder.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /root/source/OpenColorIO/ext/yaml-cpp/src/contrib/graphbuilder.cpp:1:0:
/root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/parser.h:47:8: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<Directives> m_pDirectives;
        ^~~~~~~~
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/memory:81:0,
                 from /root/source/OpenColorIO/ext/yaml-cpp/include/yaml-cpp/parser.h:12,
                 from /root/source/OpenColorIO/ext/yaml-cpp/src/contrib/graphbuilder.cpp:1:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[100%] Linking CXX static library libyaml-cpp.a
[100%] Built target yaml-cpp
[  9%] Performing install step for 'YAML_CPP_LOCAL'
[100%] Built target yaml-cpp
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /root/source/OpenColorIO/ext/dist/lib/libyaml-cpp.a
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/emitter.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/anchor.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/emitfromevents.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/aliasmanager.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/parser.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/yaml.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/binary.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/nodereadimpl.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/nodeutil.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/stlnode.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/ostream.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/traits.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/exceptions.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/dll.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/iterator.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/mark.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/contrib
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/contrib/graphbuilder.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/contrib/anchordict.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/eventhandler.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/nodeimpl.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/node.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/noncopyable.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/stlemitter.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/ltnode.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/emittermanip.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/conversion.h
-- Installing: /root/source/OpenColorIO/ext/dist/include/yaml-cpp/null.h
-- Installing: /root/source/OpenColorIO/ext/dist/lib/pkgconfig/yaml-cpp.pc
[ 10%] Completed 'YAML_CPP_LOCAL'
[ 10%] Built target YAML_CPP_LOCAL
Scanning dependencies of target OpenColorIO_STATIC
Scanning dependencies of target OpenColorIO
[ 10%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/AllocationOp.cpp.o
[ 10%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/AllocationOp.cpp.o
[ 11%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/AllocationTransform.cpp.o
[ 12%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/AllocationTransform.cpp.o
[ 12%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/Baker.cpp.o
[ 12%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/Baker.cpp.o
[ 12%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/CDLTransform.cpp.o
[ 13%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/CDLTransform.cpp.o
[ 13%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/Caching.cpp.o
[ 14%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/Caching.cpp.o
[ 14%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/ColorSpace.cpp.o
[ 14%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/ColorSpace.cpp.o
[ 15%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/ColorSpaceTransform.cpp.o
[ 16%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/ColorSpaceTransform.cpp.o
[ 16%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/Config.cpp.o
[ 16%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/Config.cpp.o
[ 16%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/Context.cpp.o
[ 16%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/Context.cpp.o
[ 17%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/Display.cpp.o
[ 18%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/Display.cpp.o
[ 18%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/DisplayTransform.cpp.o
[ 18%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/DisplayTransform.cpp.o
[ 19%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/Exception.cpp.o
[ 20%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/Exception.cpp.o
[ 20%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/ExponentOps.cpp.o
[ 20%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/ExponentOps.cpp.o
[ 20%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/ExponentTransform.cpp.o
[ 20%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/ExponentTransform.cpp.o
[ 21%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileFormat3DL.cpp.o
[ 22%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileFormat3DL.cpp.o
[ 22%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileFormatCC.cpp.o
[ 22%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileFormatCC.cpp.o
[ 22%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileFormatCCC.cpp.o
[ 22%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileFormatCCC.cpp.o
[ 23%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileFormatCDL.cpp.o
[ 24%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileFormatCDL.cpp.o
[ 24%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileFormatCSP.cpp.o
[ 24%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileFormatCSP.cpp.o
[ 25%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileFormatHDL.cpp.o
[ 26%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileFormatHDL.cpp.o
[ 26%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileFormatIridasCube.cpp.o
[ 26%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileFormatIridasCube.cpp.o
[ 26%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileFormatIridasItx.cpp.o
[ 26%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileFormatIridasItx.cpp.o
[ 27%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileFormatIridasLook.cpp.o
[ 28%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileFormatIridasLook.cpp.o
[ 28%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileFormatPandora.cpp.o
[ 28%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileFormatPandora.cpp.o
[ 28%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileFormatSpi1D.cpp.o
[ 29%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileFormatSpi1D.cpp.o
[ 29%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileFormatSpi3D.cpp.o
[ 30%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileFormatSpi3D.cpp.o
[ 30%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileFormatSpiMtx.cpp.o
[ 30%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileFormatSpiMtx.cpp.o
[ 31%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileFormatTruelight.cpp.o
[ 32%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileFormatTruelight.cpp.o
[ 32%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileFormatVF.cpp.o
[ 32%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileFormatVF.cpp.o
[ 32%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/FileTransform.cpp.o
[ 32%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/FileTransform.cpp.o
[ 33%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/GpuShaderDesc.cpp.o
[ 34%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/GpuShaderDesc.cpp.o
[ 34%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/GpuShaderUtils.cpp.o
[ 34%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/GpuShaderUtils.cpp.o
[ 35%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/GroupTransform.cpp.o
[ 36%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/GroupTransform.cpp.o
[ 36%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/HashUtils.cpp.o
[ 36%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/HashUtils.cpp.o
[ 36%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/ImageDesc.cpp.o
[ 36%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/ImageDesc.cpp.o
[ 37%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/ImagePacking.cpp.o
[ 38%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/ImagePacking.cpp.o
[ 38%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/LogOps.cpp.o
[ 38%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/LogOps.cpp.o
[ 38%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/LogTransform.cpp.o
[ 38%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/LogTransform.cpp.o
[ 39%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/Logging.cpp.o
[ 40%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/Logging.cpp.o
[ 40%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/Look.cpp.o
[ 40%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/Look.cpp.o
[ 41%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/LookParse.cpp.o
[ 42%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/LookParse.cpp.o
[ 42%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/LookTransform.cpp.o
[ 42%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/LookTransform.cpp.o
[ 42%] Building CXX object src/core/CMakeFiles/OpenColorIO_STATIC.dir/Lut1DOp.cpp.o
[ 42%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/Lut1DOp.cpp.o
/root/source/OpenColorIO/src/core/Lut1DOp.cpp:192:14: error: 'void OpenColorIO::v1::{anonymous}::Lut1D_Nearest(float*, long int, const OpenColorIO::v1::Lut1D&)' defined but not used [-Werror=unused-function]
         void Lut1D_Nearest(float* rgbaBuffer, long numPixels, const Lut1D & lut)
              ^~~~~~~~~~~~~
/root/source/OpenColorIO/src/core/Lut1DOp.cpp:192:14: error: 'void OpenColorIO::v1::{anonymous}::Lut1D_Nearest(float*, long int, const OpenColorIO::v1::Lut1D&)' defined but not used [-Werror=unused-function]
         void Lut1D_Nearest(float* rgbaBuffer, long numPixels, const Lut1D & lut)
              ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [src/core/CMakeFiles/OpenColorIO_STATIC.dir/Lut1DOp.cpp.o] Error 1
src/core/CMakeFiles/OpenColorIO_STATIC.dir/build.make:608: recipe for target 'src/core/CMakeFiles/OpenColorIO_STATIC.dir/Lut1DOp.cpp.o' failed
CMakeFiles/Makefile2:237: recipe for target 'src/core/CMakeFiles/OpenColorIO_STATIC.dir/all' failed
make[1]: *** [src/core/CMakeFiles/OpenColorIO_STATIC.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 43%] Building CXX object src/core/CMakeFiles/OpenColorIO.dir/Lut3DOp.cpp.o
cc1plus: all warnings being treated as errors
make[2]: *** [src/core/CMakeFiles/OpenColorIO.dir/Lut1DOp.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
src/core/CMakeFiles/OpenColorIO.dir/build.make:608: recipe for target 'src/core/CMakeFiles/OpenColorIO.dir/Lut1DOp.cpp.o' failed
make[1]: *** [src/core/CMakeFiles/OpenColorIO.dir/all] Error 2
CMakeFiles/Makefile2:199: recipe for target 'src/core/CMakeFiles/OpenColorIO.dir/all' failed
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c cd ~/source && 	git clone https://github.com/imageworks/OpenColorIO.git && 	cd OpenColorIO && 	git checkout tags/v1.1.0 && 	source scl_source enable devtoolset-6 && 	scl enable devtoolset-6 bash && 	cmake --DCMAKE_INSTALL_PREFIX:PATH=/usr/local --OCIO_BUILD_GPU_TESTS=OFF . && 	make -j2 && 	make install' returned a non-zero code: 2
````

### PR DESCRIPTION
**Pull request by zicklag**
Fixes #617.

I'm not 100% sure I'm understanding this correctly, but when SSE is enabled, in `Lut1DOp.cpp` the compiler complains because `Lut1D_Nearest()` is defined but not used. The function *is* used in the unit tests, so we include it only when SSE is disabled or we are compiling unit tests.

For `MathUtils.cpp` it is a similar story, but for some reason, even with SSE disabled, the compiler will complain that the `GetMxbResult()` function is defined but not used for the DLL (.so) build. The function *is* used for the static build of the library, so we include it in the static build and the unit tests.

The tests will run successfully, but I've only tested on Linux.

Tell me if I'm missing anything! :smiley:

### CODE REVIEW

**Comment by zicklag** [comment]
It looks Travis [failed](https://travis-ci.org/imageworks/OpenColorIO/jobs/497632599#L852), but I don't think it is related to the PR:

```
Download error on https://pypi.python.org/simple/markupsafe/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
Couldn't find index page for 'markupsafe' (maybe misspelled?)
```

**Comment by hodoulp** [comment]
@zicklag Last minute bad surprises but the CI build breaks are not related to your pull request. These problems will soon be fixed.

File: src/core/MathUtils.cpp [hunk 1]
```diff
@@ -330,11 +330,13 @@ OCIO_NAMESPACE_ENTER
     namespace
     {
     
+#if defined(OpenColorIO_Static) || defined(OCIO_UNIT_TEST)
```
Comment (hodoulp) [inline src/core/MathUtils.cpp]: > defined(OpenColorIO_Static)

Why did you add the 'static lib.' condition (i.e. unit test condition seems enough)?

Comment (zicklag) [reply src/core/MathUtils.cpp]: It looks like that did work. During my testing earlier I thought that I had tried that and that it complained that the function was not defined for the Static lib. Looks like I had something else wrong. I'll fix that.
